In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
import os
pd.set_option('display.max_columns', None)

In [2]:
print(os.getcwd())

C:\Users\yjany\week 4-5\notebooks

In [3]:
os.listdir("../Driver Behavior and Route Anomaly Dataset")

['.ipynb_checkpoints',
 'driver_behavior_route_anomaly_dataset_with_derived_features.csv']

In [4]:
df = pd.read_csv("../Driver Behavior and Route Anomaly Dataset/driver_behavior_route_anomaly_dataset_with_derived_features.csv")

In [5]:
df

,trip_id,driver_id,vehicle_id,timestamp,latitude,longitude,speed,acceleration,steering_angle,heading,trip_duration,trip_distance,fuel_consumption,rpm,brake_usage,lane_deviation,weather_conditions,road_type,traffic_condition,stop_events,geofencing_violation,anomalous_event,route_anomaly,route_deviation_score,acceleration_variation,behavioral_consistency_index
0,1,101,1001,2023-01-01 00:00:00,38.916143,-80.345269,39.484646,3.612832,6,212.555994,250.980424,24.868334,19.293594,8300.855056,3,0.065983,Sunny,Urban,Light,0,0,0,0,0.176974,0.715284,0.468189
1,2,105,2002,2023-01-01 00:00:01,37.011830,-89.079516,2.795422,-0.593295,-21,134.541146,2112.678280,10.230086,2.011132,2290.934075,5,0.571305,Sunny,Highway,Light,0,0,1,0,0.229316,0.487761,0.234935
2,3,103,2002,2023-01-01 00:00:02,33.784009,-99.103643,13.842558,-0.209264,26,116.452839,1134.936064,23.483279,4.025824,1299.930836,5,0.402290,Cloudy,Urban,Moderate,0,0,0,0,0.473809,0.881141,0.192588
3,4,102,2002,2023-01-01 00:00:03,45.314835,-102.046210,69.121833,-0.413943,6,26.970247,11651.719966,1.480827,1.233628,3825.966601,5,0.079944,Sunny,Highway,Moderate,3,0,0,0,0.368063,0.937918,0.363707
4,5,101,2002,2023-01-01 00:00:04,30.473386,-92.362577,13.061111,5.774122,-1,333.804023,1033.826911,131.294800,2.720884,2376.000694,4,0.289152,Sunny,Rural,Moderate,0,0,0,0,0.145270,0.702187,0.178748
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,119996,101,1001,2023-01-02 09:19:55,43.054036,-86.197119,10.263763,-0.802541,18,53.521771,106.782437,76.864084,1.597314,544.999111,6,0.346934,Sunny,Urban,Moderate,0,0,0,0,0.232350,0.375641,0.067177
119996,119997,101,2002,2023-01-02 09:19:56,35.551541,-73.439461,40.431564,-0.532927,18,86.945711,222.929189,3.652979,2.268303,986.879359,4,0.527412,Foggy,Urban,Moderate,1,1,1,0,0.431830,0.822901,0.096263
119997,119998,101,1001,2023-01-02 09:19:57,41.964624,-95.333223,53.893048,0.734331,7,288.027901,5242.739960,51.478409,2.545001,1509.988839,2,0.592113,Rainy,Highway,Moderate,2,0,0,0,0.089747,0.817555,0.171400
119998,119999,101,2002,2023-01-02 09:19:58,30.356801,-79.892936,65.559146,0.366847,-11,249.409519,8280.662297,41.997598,4.805905,1010.639388,5,0.296826,Cloudy,Urban,Light,1,0,0,0,0.614545,0.798756,0.452616
119999,120000,101,1001,2023-01-02 09:19:59,32.707254,-92.526916,10.351467,-0.321536,2,71.344715,1445.700033,7.013732,3.225019,1503.106072,5,0.400639,Cloudy,Urban,Moderate,2,0,0,0,0.150682,0.753897,0.393896

In [6]:
df.dtypes

trip_id                           int64
driver_id                         int64
vehicle_id                        int64
timestamp                        object
latitude                        float64
longitude                       float64
speed                           float64
acceleration                    float64
steering_angle                    int64
heading                         float64
trip_duration                   float64
trip_distance                   float64
fuel_consumption                float64
rpm                             float64
brake_usage                       int64
lane_deviation                  float64
weather_conditions               object
road_type                        object
traffic_condition                object
stop_events                       int64
geofencing_violation              int64
anomalous_event                   int64
route_anomaly                     int64
route_deviation_score           float64
acceleration_variation          float64
behavioral_consistency_index    float64
dtype: object

In [7]:
pd.set_option('display.precision', 2)

In [8]:
df

,trip_id,driver_id,vehicle_id,timestamp,latitude,longitude,speed,acceleration,steering_angle,heading,trip_duration,trip_distance,fuel_consumption,rpm,brake_usage,lane_deviation,weather_conditions,road_type,traffic_condition,stop_events,geofencing_violation,anomalous_event,route_anomaly,route_deviation_score,acceleration_variation,behavioral_consistency_index
0,1,101,1001,2023-01-01 00:00:00,38.92,-80.35,39.48,3.61,6,212.56,250.98,24.87,19.29,8300.86,3,0.07,Sunny,Urban,Light,0,0,0,0,0.18,0.72,0.47
1,2,105,2002,2023-01-01 00:00:01,37.01,-89.08,2.80,-0.59,-21,134.54,2112.68,10.23,2.01,2290.93,5,0.57,Sunny,Highway,Light,0,0,1,0,0.23,0.49,0.23
2,3,103,2002,2023-01-01 00:00:02,33.78,-99.10,13.84,-0.21,26,116.45,1134.94,23.48,4.03,1299.93,5,0.40,Cloudy,Urban,Moderate,0,0,0,0,0.47,0.88,0.19
3,4,102,2002,2023-01-01 00:00:03,45.31,-102.05,69.12,-0.41,6,26.97,11651.72,1.48,1.23,3825.97,5,0.08,Sunny,Highway,Moderate,3,0,0,0,0.37,0.94,0.36
4,5,101,2002,2023-01-01 00:00:04,30.47,-92.36,13.06,5.77,-1,333.80,1033.83,131.29,2.72,2376.00,4,0.29,Sunny,Rural,Moderate,0,0,0,0,0.15,0.70,0.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,119996,101,1001,2023-01-02 09:19:55,43.05,-86.20,10.26,-0.80,18,53.52,106.78,76.86,1.60,545.00,6,0.35,Sunny,Urban,Moderate,0,0,0,0,0.23,0.38,0.07
119996,119997,101,2002,2023-01-02 09:19:56,35.55,-73.44,40.43,-0.53,18,86.95,222.93,3.65,2.27,986.88,4,0.53,Foggy,Urban,Moderate,1,1,1,0,0.43,0.82,0.10
119997,119998,101,1001,2023-01-02 09:19:57,41.96,-95.33,53.89,0.73,7,288.03,5242.74,51.48,2.55,1509.99,2,0.59,Rainy,Highway,Moderate,2,0,0,0,0.09,0.82,0.17
119998,119999,101,2002,2023-01-02 09:19:58,30.36,-79.89,65.56,0.37,-11,249.41,8280.66,42.00,4.81,1010.64,5,0.30,Cloudy,Urban,Light,1,0,0,0,0.61,0.80,0.45
119999,120000,101,1001,2023-01-02 09:19:59,32.71,-92.53,10.35,-0.32,2,71.34,1445.70,7.01,3.23,1503.11,5,0.40,Cloudy,Urban,Moderate,2,0,0,0,0.15,0.75,0.39

In [9]:
df=df[['trip_id', 'driver_id', 'timestamp', 'latitude', 'longitude',
       'speed', 'acceleration', 'steering_angle', 'trip_duration',
       'trip_distance', 'fuel_consumption', 'brake_usage', 'weather_conditions',
       'road_type', 'traffic_condition', 'stop_events', 'geofencing_violation', 
       'anomalous_event', 'route_anomaly', 'route_deviation_score',	'acceleration_variation', 'behavioral_consistency_index']].copy()

In [10]:
df

,trip_id,driver_id,timestamp,latitude,longitude,speed,acceleration,steering_angle,trip_duration,trip_distance,fuel_consumption,brake_usage,weather_conditions,road_type,traffic_condition,stop_events,geofencing_violation,anomalous_event,route_anomaly,route_deviation_score,acceleration_variation,behavioral_consistency_index
0,1,101,2023-01-01 00:00:00,38.92,-80.35,39.48,3.61,6,250.98,24.87,19.29,3,Sunny,Urban,Light,0,0,0,0,0.18,0.72,0.47
1,2,105,2023-01-01 00:00:01,37.01,-89.08,2.80,-0.59,-21,2112.68,10.23,2.01,5,Sunny,Highway,Light,0,0,1,0,0.23,0.49,0.23
2,3,103,2023-01-01 00:00:02,33.78,-99.10,13.84,-0.21,26,1134.94,23.48,4.03,5,Cloudy,Urban,Moderate,0,0,0,0,0.47,0.88,0.19
3,4,102,2023-01-01 00:00:03,45.31,-102.05,69.12,-0.41,6,11651.72,1.48,1.23,5,Sunny,Highway,Moderate,3,0,0,0,0.37,0.94,0.36
4,5,101,2023-01-01 00:00:04,30.47,-92.36,13.06,5.77,-1,1033.83,131.29,2.72,4,Sunny,Rural,Moderate,0,0,0,0,0.15,0.70,0.18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119995,119996,101,2023-01-02 09:19:55,43.05,-86.20,10.26,-0.80,18,106.78,76.86,1.60,6,Sunny,Urban,Moderate,0,0,0,0,0.23,0.38,0.07
119996,119997,101,2023-01-02 09:19:56,35.55,-73.44,40.43,-0.53,18,222.93,3.65,2.27,4,Foggy,Urban,Moderate,1,1,1,0,0.43,0.82,0.10
119997,119998,101,2023-01-02 09:19:57,41.96,-95.33,53.89,0.73,7,5242.74,51.48,2.55,2,Rainy,Highway,Moderate,2,0,0,0,0.09,0.82,0.17
119998,119999,101,2023-01-02 09:19:58,30.36,-79.89,65.56,0.37,-11,8280.66,42.00,4.81,5,Cloudy,Urban,Light,1,0,0,0,0.61,0.80,0.45
119999,120000,101,2023-01-02 09:19:59,32.71,-92.53,10.35,-0.32,2,1445.70,7.01,3.23,5,Cloudy,Urban,Moderate,2,0,0,0,0.15,0.75,0.39

In [13]:
df.isna().sum()

trip_id                         0
driver_id                       0
timestamp                       0
latitude                        0
longitude                       0
speed                           0
acceleration                    0
steering_angle                  0
trip_duration                   0
trip_distance                   0
fuel_consumption                0
brake_usage                     0
weather_conditions              0
road_type                       0
traffic_condition               0
stop_events                     0
geofencing_violation            0
anomalous_event                 0
route_anomaly                   0
route_deviation_score           0
acceleration_variation          0
behavioral_consistency_index    0
dtype: int64

In [12]:
df.loc[df.duplicated()]

Empty DataFrame
Columns: [trip_id, driver_id, timestamp, latitude, longitude, speed, acceleration, steering_angle, trip_duration, trip_distance, fuel_consumption, brake_usage, weather_conditions, road_type, traffic_condition, stop_events, geofencing_violation, anomalous_event, route_anomaly, route_deviation_score, acceleration_variation, behavioral_consistency_index]
Index: []

In [14]:
print(df['stop_events'].value_counts())

stop_events
0    44419
1    44077
2    21764
3     7472
4     1837
5      352
6       67
7       11
8        1
Name: count, dtype: int64

In [15]:
df.shape

(120000, 22)

In [16]:
print(df['driver_id'].value_counts())

driver_id
101    59888
102    24163
104    12204
103    11945
105    11800
Name: count, dtype: int64

In [17]:
df.to_csv("../Driver Behavior and Route Anomaly Dataset/driver_behavior_cleaned.csv", index=False)
print("Saved successfully!")

Saved successfully!

In [1]:
import os
os.listdir("..")

['.ipynb_checkpoints',
 'Delivery truck trips data',
 'DeliveryTruckTripsData_cleaned.ipynb',
 'Driver Behavior and Route Anomaly Dataset',
 'Driving Behavior',
 'Highway Traffic Videos',
 'notebooks',
 'Traffic_Violations.csv',
 'Transportation ang Logistics Tracking Datasets',
 'Untitled.ipynb',
 'Yolo Truck Datasets']