In [1]:
import pandas as pd
import numpy as np
import matplotlib.pylab as plt
import seaborn as sns
import os
pd.set_option('display.max_columns', None)

In [4]:
print(os.getcwd())

C:\Users\yjany\week 4-5\notebooks

In [5]:
os.listdir("../Driving Behavior")

['test_motion_data.csv', 'train_motion_data.csv']

In [6]:
df_train = pd.read_csv("../Driving Behavior/train_motion_data.csv")
df_test = pd.read_csv("../Driving Behavior/test_motion_data.csv")

In [7]:
df_train

,AccX,AccY,AccZ,GyroX,GyroY,GyroZ,Class,Timestamp
0,0.000000,0.000000,0.000000,0.059407,-0.174707,0.101938,NORMAL,3581629
1,-1.624864,-1.082492,-0.204183,-0.028558,0.051313,0.135536,NORMAL,3581630
2,-0.594660,-0.122410,0.220502,-0.019395,-0.029322,0.087888,NORMAL,3581630
3,0.738478,-0.228456,0.667732,0.069791,-0.029932,0.054902,NORMAL,3581631
4,0.101741,0.777568,-0.066730,0.030696,-0.003665,0.054902,NORMAL,3581631
...,...,...,...,...,...,...,...,...
3639,0.915688,-2.017489,1.687505,0.450360,0.384845,-1.236468,SLOW,3583789
3640,-1.934203,0.914925,-0.096013,0.321468,0.649350,-0.477162,SLOW,3583790
3641,-0.222845,0.747304,-0.887430,0.361174,-0.406836,0.054291,SLOW,3583790
3642,-0.349423,0.067261,0.394368,-0.132405,0.020159,-0.004963,SLOW,3583791
3643,-0.402428,0.406218,-0.423009,-0.053603,-0.006720,0.001145,SLOW,3583791

In [8]:
df_test

,AccX,AccY,AccZ,GyroX,GyroY,GyroZ,Class,Timestamp
0,0.758194,-0.217791,0.457263,0.000000,0.000000,0.000000,AGGRESSIVE,818922
1,0.667560,-0.038610,0.231416,-0.054367,-0.007712,0.225257,AGGRESSIVE,818923
2,2.724449,-7.584121,2.390926,0.023824,0.013668,-0.038026,AGGRESSIVE,818923
3,2.330950,-7.621754,2.529024,0.056810,-0.180587,-0.052076,AGGRESSIVE,818924
4,2.847215,-6.755621,2.224640,-0.031765,-0.035201,0.035277,AGGRESSIVE,818924
...,...,...,...,...,...,...,...,...
3079,-0.713858,-0.652975,-0.164015,-0.147829,-1.309466,0.517250,SLOW,820706
3080,1.514261,0.330070,1.020714,1.321302,1.707598,-0.674548,SLOW,820707
3081,1.280216,-1.735172,-2.332695,0.583376,0.690507,-0.468075,SLOW,820707
3082,0.912313,0.583314,-0.965622,0.235794,0.512745,0.406073,SLOW,820708
3083,1.462172,0.190287,0.019377,-0.254731,-0.279547,0.076205,SLOW,820709

In [9]:
df_train['Class'].value_counts()

Class
SLOW          1331
NORMAL        1200
AGGRESSIVE    1113
Name: count, dtype: int64

In [10]:
df_test['Class'].value_counts()

Class
SLOW          1273
NORMAL         997
AGGRESSIVE     814
Name: count, dtype: int64

In [11]:
df_train.isna().sum()

AccX         0
AccY         0
AccZ         0
GyroX        0
GyroY        0
GyroZ        0
Class        0
Timestamp    0
dtype: int64

In [12]:
df_test.isna().sum()

AccX         0
AccY         0
AccZ         0
GyroX        0
GyroY        0
GyroZ        0
Class        0
Timestamp    0
dtype: int64

In [13]:
df_train.to_csv("../Driving Behavior/driving_behavior_train_cleaned.csv", index=False)
df_test.to_csv("../Driving Behavior/driving_behavior_test_cleaned.csv", index=False)
print("Saved successfully!")

Saved successfully!